# Generated by Django 4.2.16 on 2024-10-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cooking_time',
        ),
    ]
