# Generated by Django 4.2.16 on 2024-10-06 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует.'}, help_text='Адрес электронной почты, не более 128 символов', max_length=128, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Имя Отчество, не более 128 символов', max_length=128, verbose_name='Имя Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Фамилия, не более 128 символов', max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует.'}, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Юзернейм может содержать только буквы, цифры и символы @/./+/-/_.', regex='^[\\w.@+-]+\\z')], verbose_name='Имя пользователя'),
        ),
    ]
