# Generated by Django 4.2.16 on 2024-10-07 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует.'}, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Юзернейм может содержать только буквы, цифры и символы @/./+/-/_.', regex='^[\\w.@+-]+\\Z')], verbose_name='Имя пользователя'),
        ),
    ]
